# Generated by Django 5.0.6 on 2024-07-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_account_order_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='coffeepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('order_id', models.CharField(blank=True, max_length=30)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=30)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='order_table',
            old_name='order_status',
            new_name='payment_status',
        ),
        migrations.AddField(
            model_name='order_table',
            name='order_id',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='order_table',
            name='pin',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
