# Generated by Django 5.0.6 on 2024-07-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_coffeepayment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coffeepayment',
            new_name='payment',
        ),
    ]
